version: "3"
services:

  api:
    container_name: bus_api
    build: api/
    ports: 
      - "8080:8080"
    volumes:
      - .:/api
    env_file:
      - ./environment/secrets/bus_api_secrets.env
      - ./environment/bus_api.env
      - ./environment/secrets/mongo_docker.env
    restart: always
    links:
      - mongo

  mongo:
      image: 'mongo'
      container_name: 'bus_db'
      env_file:
        - ./environment/secrets/mongo_docker.env
      volumes:
        - ./api/db/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
        - ./data:/data/db
      ports:
        - '27017-27019:27017-27019'
      command: mongod
